FROM {{FROM_IMAGE_NAME}}

RUN apt-get update && \
    apt-get install -y libb64-dev libb64-0d libffi-dev libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/workspace

RUN pip install onnx
RUN pip install --upgrade --upgrade-strategy only-if-needed \
    {{INSTALL_URL}}

ADD {{DEPLOYER_LOCAL}} {{DEPLOYER_DOCKER}}
ADD {{TESTER_LOCAL}} {{TESTER_DOCKER}}

