FROM {{FROM_IMAGE_NAME}}

RUN apt-get update && \
    apt-get install -y --no-install-recommends libb64-dev libb64-0d libffi-dev libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/workspace

# onnx is required by graph_surgeon
RUN pip install --no-cache-dir onnx && \
    pip install --no-cache-dir --upgrade --upgrade-strategy only-if-needed \
    {{INSTALL_URL}}

COPY {{DEPLOYER_LOCAL}} {{DEPLOYER_DOCKER}}
COPY {{EVALUATOR_LOCAL}} {{EVALUATOR_DOCKER}}
COPY {{CONFIG_LOCAL}} {{CONFIG_DOCKER}}

